/* =====================================================================
   KATEGORİLER
   ===================================================================== */
const KAT = {
  vaka:      { ad:"Vaka & Öncelik",       renk:"#ff6b8b" },
  vital:     { ad:"Vital Bulgular",        renk:"#f97316" },
  solunum:   { ad:"Solunum Sistemi",       renk:"#38bdf8" },
  kardiyo:   { ad:"Kardiyovasküler",       renk:"#fb7185" },
  sinir:     { ad:"Sinir Sistemi",         renk:"#a78bfa" },
  sivi:      { ad:"Sıvı & Elektrolit",     renk:"#22d3ee" },
  enfeksiyon:{ ad:"Enfeksiyon & İzolasyon",renk:"#f59e0b" },
  farmako:   { ad:"Farmakoloji",           renk:"#34d399" },
  endokrin:  { ad:"Endokrin & Diyabet",    renk:"#f472b6" },
  cerrahi:   { ad:"Cerrahi Bakım",         renk:"#fb923c" },
  kan:       { ad:"Kan Transfüzyonu",      renk:"#ef4444" },
  cocuk:     { ad:"Çocuk Sağlığı",         renk:"#2dd4bf" },
  dogum:     { ad:"Kadın Doğum",           renk:"#f9a8d4" },
  ilkyardim: { ad:"İlk Yardım & CPR",      renk:"#facc15" },
  guvenlik:  { ad:"Hasta Güvenliği",       renk:"#94a3b8" }
};

/* =====================================================================
   SORU BANKASI
   t: bilgi | vaka
   k: kategori   z: zorluk 1-3
   d: doğru şık indeksi   a: açıklama
   ===================================================================== */
const SORULAR = [

/* ---------------- VAKA & ÖNCELİK ---------------- */
{ t:"vaka", k:"vaka", z:2,
  hasta:{ ad:"Mehmet K.", yas:58, c:"Erkek",
    sikayet:"Göğsünün ortasında sıkışma, kollarıma yayılan ağrı. 40 dakika önce başladı, dinlenince geçmiyor." },
  vital:{ TA:"148/92", nabiz:"96", solunum:"22", SpO2:"%93", GKS:"15", Aci:"8/10" },
  s:"Bu hastada ilk olarak ne yaparsın?",
  o:["Aspirin 300 mg çiğnet, hastayı yarı oturur pozisyona getir, 12 kanalı EKG çek ve monitöre bağla",
     "Hastaya yatak istirahati ver, saatlik kontrol ile bekle",
     "Hastayı hemen yoğun bakıma sevk et, tanıyı acil serviste netleştirme",
     "İçecek ısıt, mide rahatsızlığı olabilir, 1 saat sonra tekrar değerlendir"],
  d:0,
  a:"Akut koronerer sendrom düşünülüyorsa ilk 10 dakika içinde: aspirin (160-325 mg), 12 kanal EKG, monitör, damar yolu ve gerekirse oksijen. Ağrı eforla artıyor, dinlenmeyle geçmiyor, çene/kola yayılıyor ve terleme eşlik ediyor: tipik miyokard infarktüsü tablosu. Mide rahatsızlığına yönelik geleneksel uygulamalar (sıcak içecek) yanlıştır ve gecikme yaratır.",
  ipucu:"İlk 10 dakika altın zamandır, EKG ve ASA birlikte." },

{ t:"vaka", k:"vaka", z:3,
  hasta:{ ad:"Ayşe D.", yas:24, c:"Kadın",
    sikayet:"Ani şiddetli karın ağrısı, karnın alt kısmına kesildi. Karnıma dokununca ağrı çok artıyor, karın tahta gibi sert." },
  vital:{ TA:"96/58", nabiz:"118", solunum:"26", SpO2:"%97", GKS:"15", Aci:"10/10" },
  s:"İlk yapılacak nedir?",
  o:["Hastaya kesinlikle yemek yedirme, genişletilmiş damar yolu aç, acil cerraha danış ve ağrıyı erken analjezikle kontrol et",
     "Ağrı kesici verme, ağrı tanıyı bozar, 2 saat bekle",
     "Sagittal abdominal röntgen çek, sonra ağrı kesici ver",
     "Kendine ilaç yaptırıp evde gönder"],
  d:0,
  a:"Ani ağrı + tahta sertlik (peritonizm) + taşikardi + hipotansiyon: akut abdomen. Rüptür veya kanama düşündürür. NPO (yememe), IV sıvı, acil cerraha konsültasyon ve analjezi çekinmeden verilmelidir. Yetersiz ağrı kontrolü komplikasyon riskini artırır; analjezi tanıyı bozmaz. Tanısal görüntüleme stabilizasyon sonrası, cerrahın yönlendirmesiyle yapılır." },

{ t:"vaka", k:"vaka", z:3,
  hasta:{ ad:"Osman K.", yas:71, c:"Erkek",
    sikayet:"Sağ kolları ve yüzünün bir tarafı hareket etmiyor. Konuşması bozuk, kendini ifade edemiyor, sabah uyandığında böyle." },
  vital:{ TA:"186/104", nabiz:"72", solunum:"18", SpO2:"%94", GKS:"6", Aci:"yok" },
  s:"En doğru yaklaşım nedir?",
  o:["Hava yolu ve solunumu güvenceye al, kan basıncını orta düzeye indir, acil nöroloji ve acil BT, kanama düşünülüyorsa pıhtılaşma ve antikoagülan öyküsü",
     "Hipotansiyon olmadığı için hastayı rahat bırak, izleme al",
     "Aspirasyon öncesi yarım doz pıhtılaştırıcı ver",
     "Sabah poliklinik randevusu ver"],
  d:0,
  a:"Ani fokal nörolojik defisit + bilinç bozukluğu (GKS 6) + yüksek tansiyon: akut inme. Önce hava yolu, solunum ve hemodinamik stabilizasyon, sonra acil nöroloji ve BT. Trombolitik tedavi sadece BT ile kanama dışlandıktan sonra, kontrendikasyon yoksa ve zaman penceresi içinde verilir. GKS 6 olan hastada endotrakeal entübasyon düşünülmelidir." },

{ t:"vaka", k:"vaka", z:2,
  hasta:{ ad:"Zeynep A.", yas:34, c:"Kadın",
    sikayet:"Diş fırçalarken diş eti kanaması, göz çevresinde morluk, kollarında ve uyluklarında morarmalar. Deplas tedavisi alıyorum." },
  vital:{ TA:"112/70", nabiz:"88", solunum:"16", SpO2:"%98", GKS:"15", Aci:"hafif" },
  s:"Bu tablo için doğru yaklaşım?",
  o:["Koagülasyon testleri (PT/INR, aPTT, trombosit, fibrinojen) iste, ilaç öyküsünü gözden geçir, sıçrama ve travma sonrası iç kanama düşün",
     "Demir eksikliği olabilir, sadece demir ilacı başla",
     "Kortikosteroid kremi öner, gingivit olabilir",
     "Psikolojik destek ver, hasta kaygın görünüyor"],
  d:0,
  a:"Antikoagülan kullanan (özellikle varfarin) hastada diş eti kanaması ve ekimozlar: koagülopati şüphesi. PT/INR, aPTT, trombosit ve fibrinojen istenir. Varfarinin teratojen etkisi nedeniyle gebelikte kullanılmaz. Yeni başlanan oral antikoagülanda özellikle ilk 3 ayda diş müdahalesinden kaçınılır. Taşikardi, hipotansiyon ve soğuk terleme varsa bu artık acil bir durumdur." },

{ t:"vaka", k:"vaka", z:1,
  hasta:{ ad:"Ali V.", yas:45, c:"Erkek",
    sikayet:"Trafik kazası sonrası acil servise geldim. Sağ omuz hareket ettirilemiyor, kol aşağıda sarkık duruyor." },
  vital:{ TA:"128/82", nabiz:"82", solunum:"18", SpO2:"%97", GKS:"15", Aci:"6/10" },
  s:"Şüpheli omuz çıkığı / üst ekstremite kırığında ilk müdahale?",
  o:["Ekstremiteyi anatomik pozisyonda sabitle (sling / kol askısı), ağrı kontrolü, damar-sinir muayenesi ve röntgen",
     "Kolu hemen çekerek yerine oturt",
     "Ağrı kesici verme, hareket ettirme, doktora haber ver ve bekle",
     "Masa başına yatır, doğru çekilmesi için uygulama yap"],
  d:0,
  a:"Emin sinir ve damar hasarını önlemek için ekstremitenin anatomik pozisyonda geçici sabitlenmesi (sling, kol askısı, spika) ilk adımdır. Luksasyonun indirilmesi ancak damar-sinir durumu değerlendirildikten, analjezi ve sedasyon sağlandıktan sonra, deneyimli ekip tarafından yapılır. Özellikle dirsek çıkığında median, ulnar ve radiyal sinir ile brakiyal artery mutlaka kontrol edilmelidir." },

{ t:"vaka", k:"vaka", z:2,
  hasta:{ ad:"Fatma H.", yas:79, c:"Kadın",
    sikayet:"2 gündür yataktan kalkamıyor, evde bakılıyor. Kalça ağrısı, iştahsızlık, son günlerde kafası bulanık." },
  vital:{ TA:"78/44", nabiz:"128", solunum:"26", SpO2:"%90", GKS:"13", Aci:"hafif" },
  s:"En olası durum ve ilk yaklaşım?",
  o:["Hipovolemik şok / sepsis: IV sıvı, kan şekeri, idrar ve böbrek fonksiyonu değerlendirmesi, oksijen, kültür ve erken empirik antibiyotik, düşmeye karşı yatak kenarı desteği",
     "Aspirin 300 mg ver ve EKG çek",
     "Diyabet ilacını iki katına çıkar",
     "Bol sıvı içir, hasta evde kalabilir"],
  d:0,
  a:"Yaşlı, yataklı, iştahsız hastada taşikardi, hipotansiyon, takipne, bilinç bulanıklığı ve idrar azalması: sepsis (idrar yolu, pnömoni, yara) veya hipovolemi. Sepsis taraması (qSOFA, laktat), kan kültürü, IV sıvı, oksijen, kan şekeri ve erken empirik antibiyotik; hipoglisemi sık ve kolayca atlanan bir nedendir. Düşme önleme: yatak kenarı, kalkışta destek, çevre düzenlemesi." },

{ t:"vaka", k:"vaka", z:2,
  hasta:{ ad:"Murat Ö.", yas:67, c:"Erkek",
    sikayet:"Bacaklarım 3 gündür şişti. Akşamları nefesim daralıyor, uyurken 2-3 yastık kullanıyorum, iştahım azaldı." },
  vital:{ TA:"158/96", nabiz:"96", solunum:"20", SpO2:"%94", GKS:"15", Aci:"yok" },
  s:"En olası tablo ve hemşirelik önceliği?",
  o:["Kalp yetmezliği: oksijen, semioturma pozisyonu, günlük kilo takibi, sıvı ve tuz kısıtlaması, diüretik uyumunun izlenmesi",
     "Ayak bileği burkulması, elastik bandaj öner",
     "Genişletilmiş sıvı replasmanı",
     "Sadece tansiyon ilacını artır, taburcu et"],
  d:0,
  a:"Çift taraflı şişlik, gündüz artan gece artan dispne, ortopne ve iştahsızlık: dekompanse kalp yetmezliği. Öncelik: oksijen (SpO2 hedefi), semioturma pozisyonu, vital bulgu ve günlük ağırlık takibi (1 kg artış yaklaşık 1000 mL sıvı retansiyonu), sıvı ve tuz kısıtlaması, diüretik ve ACE inhibitörü uyumunun izlenmesi. Ağırlık artışı, gece öksürüğü ve artan ödem dekompansasyon alarmıdır." },

{ t:"vaka", k:"vaka", z:2,
  hasta:{ ad:"Büşra T.", yas:26, c:"Kadın",
    sikayet:"Göğsünün sağ altında keskin ağrı, öksürünce ve derin nefes alınca çok artıyor. Hafif ateş ve kuru öksürük." },
  vital:{ TA:"118/76", nabiz:"92", solunum:"20", SpO2:"%97", GKS:"15", Aci:"5/10" },
  s:"En olası tablo ve ilk yaklaşım?",
  o:["Pnömotiroid veya plevrit düşün; EKG ile miyokard infarktüsü ekarte et, yarı oturma, istirahati ve analjezi, gerekirse akciğer grafisi",
     "Kesin pnömokok pnömonisi, hemen antibiyotik ver ve taburcu et",
     "Tansiyon yüksekliği, tansiyon ilacını artır",
     "Göğüs ağrısı, EKG gerekmez"],
  d:0,
  a:"Solunumla ilişkili keskin göğüs ağrısı, öksürük ve kuru öksürük: pnömotiroid, plevrit, atelektazi, kaburga kırığı veya herpes zoster düşündürür. EKG ile miyokard infarktüsü (özellikle inferior duvar) ekarte edilmelidir. Ağrıyı azaltmak için yatak istirahati, yarı oturma pozisyonu ve analjezi; ardından akciğer grafisi ve kan sayımı." },

{ t:"vaka", k:"vaka", z:3,
  hasta:{ ad:"Kemal A.", yas:52, c:"Erkek",
    sikayet:"Tansiyon ilacını 3 gün önce kendim kestim. 3 gündür çok şiddetli baş ağrısı, bulantı-kusma, görme bulanıklığı, sağ kolumda güç kaybı var." },
  vital:{ TA:"228/128", nabiz:"62", solunum:"18", SpO2:"%96", GKS:"12", Aci:"yok" },
  s:"En olası tablo ve acil yönetim?",
  o:["Hipertansif acil: yoğun bakımda ABP izlemi, kontrollü kademeli düşürme (ilk saatte ortalama arter basıncı en fazla %25), acil nöroloji ve BT",
     "Anjiyotensif ilacı hızlı ve bol ver, kan basıncını hemen normalleştir",
     "Evde takip ve ilacı kademeli geri başlat",
     "Diuretik infüzyonu tek başına yeterlidir"],
  d:0,
  a:"Ağır hipertansiyon + akut hedef organ hasarı (nörolojik bulgu, görme bozukluğu, bilinç değişikliği): hipertansif acil. Yönetim: yoğun bakımda arteriyel basınç izlemi, hedeflenen azaltma (ilk saatte MAP en fazla %25 düşer, sonraki 2-6 saatte 160/100-110 hedefi, sonra yavaş). İlaç: IV nikardipin, labetalol, nitroprüssid, esmolol; beta bloker tek başına ve ACE inhibitörü + ARB birlikte kontrendikedir. Acil BT ve nöroloji konsültasyonu şarttır; antikoagülan kararı görüntüleme öncesi verilmez." },

/* ---------------- VİTAL BULGULAR ---------------- */
{ t:"bilgi", k:"vital", z:1,
  s:"Erişkinde normal nabız hızı nedir?",
  o:["40-60/dk","60-100/dk","100-120/dk","120-140/dk"], d:1,
  a:"Erişkin dinlenme nabzı 60-100/dakikadır. 1 yaş altı 100-160, çocuklukta 80-120/dk. Yaşlanma ile dinlenme nabzı değişmez, egzersizdeki maksimum nabız azalır." },

{ t:"bilgi", k:"vital", z:1,
  s:"Erişkinde normal solunum sayısı aralığı nedir?",
  o:["6-10/dk","12-20/dk","20-28/dk","8-16/dk"], d:1,
  a:"Erişkinde 12-20/dakika normaldir. Yenidoğanda 30-60, bebekte 20-30, çocukta 20-25, ergende 12-20/dk. Solunum bir dakika sayılmalıdır. Çocukluk dönemi hastalıklarında en erken bozulan vital bulgudur." },

{ t:"bilgi", k:"vital", z:2,
  s:"Vücut sıcaklığı hangi bölgeden ölçüldüğünde en yüksek değeri verir?",
  o:["Aksilla","Ağız (oral)","Rektum (rektal)","Bacak (baldır)"], d:2,
  a:"Sıcaklık bölgeye göre değişir: en düşük aksilla, en yüksek rektum. Rektum aksilladan yaklaşık 0,3-0,5 derece daha yüksektir. Ağız içi ölçümde dudaklar kapalı olmalıdır. Yenidoğanda timpanik ve aksiller ölçüm tercih edilir; alın termometresi düşük okuduğu için artırılmış değerlendirilir." },

{ t:"bilgi", k:"vital", z:2,
  s:"Normal diastolik kan basıncı değeri aralığı nedir?",
  o:["40-55 mmHg","60-90 mmHg","95-110 mmHg","110-130 mmHg"], d:1,
  a:"Normal kan basıncı 100-130/60-90 mmHg'dir. Sistolik 140 ve üzeri, diastolik 90 ve üzeri hipertansiyon kabul edilir. Manşet, kalp düzeyinde (brakiyal arter hizasında) ve kol çevresinin yüzde 20-30 fazlası genişlikte olmalıdır. Obez hastada küçük manşet sonucu yükseltir." },

{ t:"bilgi", k:"vital", z:2,
  s:"Pulse oksimetrede normal SpO2 değeri nedir?",
  o:["%80-88","%88-93","%95-100","%99-100"], d:2,
  a:"Normal SpO2 %95-100 arasındadır; %91-94 hipoksemi sınıfındadır. KOAH gibi hiperkapnik hastalarda hedef genellikle %88-92 tutulur, çünkü kontrolsüz oksijen CO2 retansiyonuna yol açabilir. Ölçüm hatalarının en sık nedenleri: soğuk ekstremite, uzun tırnak, hareket, düşük perfüzyon." },

{ t:"bilgi", k:"vital", z:2,
  s:"Tırnak kapillaser dolum süresi normalde kaç saniyedir?",
  o:["1 saniye","2-3 saniye","5 saniye","10 saniye"], d:1,
  a:"Normal kapiller dolum süresi 2-3 saniyedir. 3-5 saniye hafif, 5 saniyeden uzun ise gecikmiş kapiller dolum düşündürür: dolaşım yetmezliği veya hipovolemi. Dehidrasyon, şok ve periferik vazokonstriksiyon bu süreyi uzatır." },

{ t:"bilgi", k:"vital", z:3,
  s:"Kan basıncı ölçümünde manşet nereye ve nasıl uygulanır?",
  o:["Bacak başparmağı, arter daha yüzeysel olduğu için",
     "Kola; manşetin alt kenarı brakiyal arter hizasına gelecek şekilde ve doğru boyutta",
     "Bileğe, taşınabilir cihazlar daha doğru ölçtüğü için","Boyun, karotis arteri daha güvenilir olduğu için"], d:1,
  a:"Kan basıncı kolun brakiyal arterinden ölçülür. Manşetin alt kenarı brakiyal arter hizasına gelmeli, kol kalp düzeyinde desteklenmelidir (otururken kalp hizası, ayakta midye hizası). Manşet, kol çevresinin yüzde 20-30 fazlası olmalıdır. Küçük manşet okumayı yükseltir, büyük manşet düşürebilir." },

/* ---------------- SOLUNUM ---------------- */
{ t:"bilgi", k:"solunum", z:2,
  s:"Astım krizinde solunum sesleri nasıl değişir?",
  o:["İnspiratuvar stridor, monotonik solunum",
     "Ekspiryum uzatılmış, bilateral yaygın wheeze (rhoncus); fıstık kabuğu benzeri ses",
     "Vokal kordi paralizisi nedeniyle bilateral stridor","Rales, iki akciğer dibinde kıt kırtırtı sesi"], d:1,
  a:"Astımda bronkospazm nedeniyle ekspiratium uzar ve bilateral yaygın wheeze duyulur. Rales (krepitan) ise pnömoni ve akciğer ödeminde duyulan kıt kırtırtı sesidir; karıştırılmamalıdır. Stridor üst hava yolu tıkanıklığında (yabancı cisim, epiglottit, laryngeal ödem) üstün üstüne nefes alma sırasında duyulur ve acil önceliktir." },

{ t:"bilgi", k:"solunum", z:3,
  s:"Pnömotoraks tablosunda hangi fizik muayene bulguları beklenir?",
  o:["İşitme ve vuruşun azalması, hiperrezonans, göğüs hareketinin azalması",
     "İşitme artışı, matite, göğüs hareketinin artması",
     "Bilateral rales ve eşit olmayan solunum sesi","Vuruş normal, deri ödemli"], d:0,
  a:"Pnömotoraksta plevra boşluğuna hava girer: o tarafta akciğer sesi kaybolur, vuruş sesi hiperrezonans olur, göğüs hareketi azalır. Tansiyon pnömotoksta trakea mediastinale kayabilir ve hemodinamik instabilite gelişir; bu durumda acil dekompresyon hayat kurtarır." },

{ t:"bilgi", k:"solunum", z:2,
  s:"Orta derecede KOAH hastasında hedeflenen SpO2 genellikle nedir?",
  o:["%99-100","%95-98","%88-92","%80-85"], d:2,
  a:"Kronik hiperkapnik hastalarda kontrolsüz oksijen vermek CO2 yükselmesine (retansiyon) ve hasta farkındalığının bozulmasına yol açabilir. Bu nedenle hedef SpO2 genellikle yüzde 88-92 aralığında tutulur ve düşük akım nazal kanül kullanılır. Gerekirse oksijen indirgeme aleti ile titrasyon yapılır." },

{ t:"bilgi", k:"solunum", z:2,
  s:"Dispneli (nefes nefese) hastada ilk müdahale nedir?",
  o:["Hastayı yatır ve yüksek doz oksijen ver",
     "Hastayı rahat ettirecek şekilde kaldır (Fowler / yarı oturma), sakinleştir, oksijen ver, gerekirse CPAP uygula",
     "Öksürük refleksini baskılayacak antitussif ver","Hastanın yürümesine izin ver"], d:1,
  a:"Dispneli hastada oturma veya yarı oturma (Fowler) pozisyonu diyafram hareketini kolaylaştırır, solunum işini azaltır. Sakin ve güven veren yaklaşım, uygun oksijen desteği ve ajitasyona göre ölçülü sedasyon esastır. Yatay pozisyon nefes darlığını artırır." },

{ t:"bilgi", k:"solunum", z:3,
  s:"Öksürürken balgam atamayan, aspirasyon riski yüksek kronik öksürüklü hastada hangi manevra uygulanır?",
  o:["Sırtına sıvaz ve göğüs fizyoterapisi",
     "Abdominal (karın) öksürük manevrası, gövde dik pozisyonda; göğüs kafesi stabil, diyaframa karşı bastırılır",
     "Uzatma pozisyonu","Yatay yatak istirahati"], d:1,
  a:"Kronik öksürükte balgam çıkaramayan hastada abdominal öksürük manevrası dikey pozisyonda uygulanır: göğüs kafesi stabil tutulur, diyaframa karşı bastırılarak öksürük refleksi güçlendirilir. Gövde dik pozisyonda, yatak başı 30-45 derece yükseltilerek drenaj kolaylaştırılır." },

{ t:"bilgi", k:"solunum", z:3,
  s:"Trakeostomi bakımında en kritik konu nedir?",
  o:["Tüpün dışarı çıkmasını (dislodgment) önlemek ve stoma bakımını hijyenik yapmak",
     "Tüpün içini sıcak suyla yıkamak",
     "Hastanın yataktan çıkmasını kesinlikle yasaklamak","Oksijeni tamamen kesmek"], d:0,
  a:"Trakeostomi komplikasyonları tüp çıkması, stomada enfeksiyon, trakea stenozu ve kazara dekanülasyondur. İlk 72 saat bant ve dikiş desteği kritiktir. Stoma kuru ve temiz tutulur; aspirasyon kuru yapılmaz, öksürme teşvik edilir. Tüpün konumu her vardiyada doğrulanır ve acil dekanülasyon ekibinin müdahale planı hazır tutulur." },

/* ---------------- KARDİYOVASKÜLER ---------------- */
{ t:"bilgi", k:"kardiyo", z:2,
  s:"Erişkin CPR'de göğüs kompresyonu derinliği ve hızı nedir?",
  o:["3-4 cm, 80-100/dk","5-6 cm, 100-120/dk","7-8 cm, 120-140/dk","3-5 cm, 60-80/dk"], d:1,
  a:"Erişkinde kompresyon derinliği en az 5 cm, en fazla 6 cm; hız 100-120/dakikadır. Kompresyonlar kaburganın tamamen yükselmesine izin verecek şekilde yapılmalıdır. 10 saniyeden uzun ara verilmemelidir. Çocukta derinlik yaklaşık 5 cm, bebekte 4 cm'dir." },

{ t:"bilgi", k:"kardiyo", z:2,
  s:"Erişkin CPR'de tek kurtarıcı için kompresyon-nefes oranı nedir?",
  o:["15:2","30:2","5:1","3:1"], d:1,
  a:"Erişkinde ve çocukta tek kurtarıcı oranı 30:2'dir. İki kurtarıcı ise çocukta 15:2, erişkinde 30:2 uygulanır. Yenidoğanda 3:1 (iki kurtarıcıda 3:2) kullanılır. Kompresyonlar duraksız ve yeterli derinlikte yapılmalıdır." },

{ t:"bilgi", k:"kardiyo", z:2,
  s:"Miyokard infarktüsünde tipik ağrı özelliği hangisidir?",
  o:["Eforla artan, 1-2 dakika sürüp dinlenince geçen, göğüste lokalize",
     "Retrosternal, eforla artan, 30 dakikadan uzun süren, dinlenmeyle geçmeyen, çene/kola/sırtta yayılan; terleme, bulantı eşlik edebilir",
     "Kol kasırt ağrısı gibi izole, hareketle artan",
     "Yemek sonrası epigastrik, hafif ve kısa süreli"], d:1,
  a:"Tipik MI ağrısı: retrosternal, sıkıştırma veya basın tarzında, eforla artan, dinlenmeyle geçmeyen, 20-30 dakikadan uzun; terleme, bulantı, dispne ve korku eşlik edebilir. Diyabet hastalarında nöropidi nedeniyle ağrısız (sessiz) infarktus olabilir. 12 kanal EKG ve troponin ile tanı, ilk dakikalarda aspirin desteği." },

{ t:"bilgi", k:"kardiyo", z:3,
  s:"Beta bloker neden miyokard infarktüsünün akil fazında rutin verilmez?",
  o:["Hiçbir neden yok, her zaman verilir",
     "Negatif inotropik etkiyle kalp yetmezliği, bradikardi ve iletim bozukluğu riskini artırır; özellikle pompa fonksiyonu bozuksa",
     "Hastayı uykusuz bırakır","Kan sulandırıcı etkisi vardır"], d:1,
  a:"Akil miyokard infarktüsünde IV beta bloker pompa fonksiyonu korunmuş ve hipotansiyon, bradikardi yoksa faydalı olabilir. Ancak pompa fonksiyonu bozulmuş hastalarda negatif inotropik etki nedeniyle kalp yetmezliği ve şok riskini artırır. Bu nedenle seçici, kademeli ve dikkatle uygulanır; IV formdan kaçınılır." },

{ t:"bilgi", k:"kardiyo", z:2,
  s:"Varfarin kullanan hastada tedavi izlemi hangi testle yapılır?",
  o:["aPTT","INR","Trombosit sayımı","Kreatinin klirensi"], d:1,
  a:"Varfarin (K vitamini antagonistleri) izlemi INR ile yapılır. Genel hedef aralık 2,0-3,0; mekanik kapak protezinde 2,5-3,5 olabilir. aPTT ise fraksiyone olmayan heparin ve düşük molekül ağırlıklı heparin izleminde kullanılır. Varfarin teratojen olduğu için gebelikte kullanılmaz." },

/* ---------------- SİNİR SİSTEMİ ---------------- */
{ t:"bilgi", k:"sinir", z:2,
  s:"Glasgow Koma Ölçeğinde 8 ve altı neyi ifade eder?",
  o:["Hafif bilinç kaybı","Orta düzey bilinç kaybı",
     "Derin bilinç bozukluğu / koma; hava yolu yönetimi değerlendirilmelidir","Uyanık ve oryante"], d:2,
  a:"GKS 13-14 hafif, 9-12 orta düzey bilinç kaybı, 8 ve altı derin bilinç bozukluğudur. Koma tanımı hiçbir uyarana (ağrı dahil) yanıt verilmemesidir. GKS 8 ve altında endotrakeal entübasyon ve mekanik ventilasyon değerlendirilmelidir. Toplam 15 üzerinden en yüksek puan raporlanır (E3V4M5 gibi)." },

{ t:"bilgi", k:"sinir", z:3,
  s:"Tek taraflı dilate ve reaktif olmayan pupilla neyi düşündürür?",
  o:["Miyozis ve sempatik uyarı","Oküler kaza, korneal irritasyon veya sempatik blok",
     "Acil nörolojik bulgu: beyin içi kanama, unkal herniasyonu; hemen nöroloji ve acil BT",
     "Normal pupilla yanıtı"], d:2,
  a:"Eşit olmayan pupil (anizokori) ve tek taraflı dilate-reaktif olmayan pupil, sempatik veya parasempatik liflerin basısıyla oluşur. Beyin içi kanama, unkal herniasyonu, metabolik ensefalopati ve anestezi sırasında görülebilir. Özellikle kafa travması sonrası acil nöroloji konsültasyonu ve acil BT gerekir; pilokarpin testi ayırıcı tanıda kullanılabilir." },

{ t:"bilgi", k:"sinir", z:2,
  s:"Epilepsi nöbeti sırasında hemşire neyi YAPMAMALI?",
  o:["Nöbeti ve süreyi izlemek","Hastayı yana yatırmak",
     "Ağzına kaşık sokmak, kollarını sıkıştırmak veya ağza su doldurmak",
     "Çevredeki sert ve kesici nesneleri uzaklaştırmak"], d:2,
  a:"Nöbet sırasında ağza bir şey sokmak dilin ısırılmasına ve diş kırılmasına, kolları sıkıştırmak humerus kırığına yol açar. Yapılması gerekenler: zamanlayıcı başlatmak, hastayı yana yatırıp aspirasyon riskini azaltmak, çevreyi temizlemek, kafa yaralanmasına karşı korumak, oksijen vermek ve kayıt tutmak. Nöbet 5 dakikayı aşarsa veya tekrarlarsa status epileptikus olarak ilaç tedavisi gerekir." },

{ t:"bilgi", k:"sinir", z:3,
  s:"Beyin kanaması şüphesinde lomber ponksiyon neden yapılmaz?",
  o:["Çünkü çok ağrılıdır",
     "Çünkü kafa içi basınç artışında herniasyon riski yaratır; önce BT ile kanama ve kitle taranmalıdır",
     "Çünkü 30 yaş üstünde yapılmaz","Çünkü hasta yatar pozisyonda olmalıdır"], d:1,
  a:"Şüpheli menenjit ve ensefalitte lomber ponksiyon tanı koydurucudur. Ancak kafa içi basınç artışı, fokal nörolojik bulgu, bilinç bozukluğu, papilödem, immünsüpresyon veya düşük GKS varsa önce BT ile kanama ve kitle taranır. Ponksiyon herniasyon riski nedeniyle BT sonrasına bırakılır. Antibiyotik tedavisi ise BT beklenirken başlatılmaz." },

{ t:"bilgi", k:"sinir", z:2,
  s:"Korneal (kornea) refleks hangi kranial sinirleri test eder?",
  o:["II - Optik","V - Trifasial ve VII - Fasial","XII - Hipoglossal","I - Olfaktor"], d:1,
  a:"Korneal refleks, V. kranial sinir (trifasial, afferent) ve VII. kranial sinir (fasial, efferent) birlikte test eder. Korneaya dokunulduğunda göz kırpılır. Korneaya değil, kenarına ıslak pamukla yaklaşılır (korneal yaralanma ve enfeksiyon riskini önlemek için). Beyin ölümü değerlendirmesinde refleks kaybı önemli bir bulgudur." },

{ t:"bilgi", k:"sinir", z:2,
  s:"Yenidoğanda fontanel kabarması ve hızlı baş çevresi artışı neyi düşündürür?",
  o:["Normal fizyolojik bulgu",
     "Hidrosefali veya kafa içi basınç artışı; acil nörolojik değerlendirme gerekli",
     "Dehidrasyonun geç bulgusu","D vitamini eksikliği"], d:1,
  a:"Bebekte fontanel, kranial süturlar tam kapanmadan önce intrakranial basıncı yansıtır. Kabarma, süturların ayrılması, hızlı artan baş çevresi ve gözlerin batarık görünümü hidrosefaliyi gösterir. Baş çevresi doğumdan itibaren seri olarak takip edilir. Erken müdahale nörolojik sekelleri ve bilişsel sorunları önler." },

/* ---------------- SIVI & ELEKTROLİT ---------------- */
{ t:"bilgi", k:"sivi", z:2,
  s:"Serum potasyumu normal aralığı nedir?",
  o:["2,5-3,5 mEq/L","3,5-5,5 mEq/L","5,0-6,5 mEq/L","6,5-7,5 mEq/L"], d:1,
  a:"Serum potasyumu 3,5-5,5 mEq/L'dir. Hipokalemi (3,5 altı) kas güçsüzlüğü, kramplar, yorgunluk, ileus ve EKG'de T düzleşmesi, U dalgası ile QT uzaması yapar. Hiperkalemi (5,5 üstü) ise sivri T, QRS genişlemesi, PR uzaması, sinüs arresti ve ventriküler aritmilere yol açar; acil tedavi gerektirir." },

{ t:"bilgi", k:"sivi", z:2,
  s:"Hiperkalemide EKG'de en erken görülen değişiklik nedir?",
  o:["QRS kompleksi genişlemesi","Sivri (sivrileşen) T dalgası","PR intervalinin uzaması","P dalgasının kaybolması"], d:1,
  a:"Hiperkalemide EKG değişiklikleri sırasıyla: sivri T dalgası, PR uzaması, P dalgasının kaybolması, QRS genişlemesi, sinüs arresti ve ventriküler fibrilasyondur. Bu nedenle potasyum yüksekliğinde acil EKG çekilmeli ve IV erişim sağlanmalıdır. Tedavi: kalsiyum glukonat (miyokard stabilizasyonu), insülin ve glukoz (hücre içi kaydırma), salbutamol, gerekiyorsa diüretik veya diyaliz." },

{ t:"bilgi", k:"sivi", z:2,
  s:"Erişkinde oligüri tanımı nedir?",
  o:["500 mL/24 saatten az","400 mL/24 saat veya 0,5 mL/kg/saatten az","1000 mL/24 saatten az","1500 mL/24 saatten az"], d:1,
  a:"Oligüri: 0,5 mL/kg/saatten az, erişkinde 400 mL/24 saat veya altında idrar çıkışıdır. Anüri 100 mL/24 saatin altıdır. Normal günlük idrar miktarı 1200-1500 mL'dir. İdrat çıkışı hemodinamik durumun ve renal fonksiyonun en değerli göstergelerinden biridir; düzenli ölçüm ve kayıt zorunludur." },

{ t:"bilgi", k:"sivi", z:2,
  s:"Arteriyel kan gazında normal pH aralığı nedir?",
  o:["7,20-7,30","7,35-7,45","7,50-7,60","7,00-7,15"], d:1,
  a:"Normal ABG: pH 7,35-7,45; PaCO2 35-45 mmHg; HCO3 22-26 mEq/L; PaO2 80-100 mmHg. pH 7,35 altı asidemi, üstü alkaliemi. PaCO2 artışı respiratuar, HCO3 artışı metabolik yönü gösterir. Değerlendirme kuralı: pH hangi tarafa kaymışsa o sistemin birincil sorunu vardır." },

{ t:"bilgi", k:"sivi", z:3,
  s:"Ağır diyare nedeniyle gelen hastada hangi asit-baz bozukluğu beklenir?",
  o:["Respiratuar asidoz (PaCO2 artar)",
     "Metabolik asidoz (HCO3 azalır, kompensatuvar PaCO2 düşer)",
     "Respiratuar alkaloz (PaCO2 düşer)","Metabolik alkaloz (HCO3 artar)"], d:1,
  a:"Gastrointestinal bikarbonat kaybı (ishal) ve laktik asit birikimi (şok) metabolik asidoz yapar. HCO3 düşer, kompansasyon olarak hiperventilasyonla PaCO2 düşer (Kussmaul solunumu). Böbrek yetmezliği ve ketoasidoz da aynı yönde gider. Solunum yetmezliğinde ise tersi: PaCO2 artar, respiratuar asidoz gelişir." },

{ t:"bilgi", k:"sivi", z:3,
  s:"Santral venöz kateterden kan alırken ilk alınan numune neden atılır?",
  o:["Numune soğuk olacağı için","Kateter içindeki sıvı (heparin veya salin) analizi dilüte eder, bu yüzden ilk 3-5 mL atılır",
     "Çünkü kırmızı tüpe alınır","Çünkü hasta aç karnına kan veriyor"], d:1,
  a:"Santral venöz kateterde ilk çekilen kan kateter içindeki sıvı ile karışıktır ve analizde kullanılamaz; genellikle 3-5 mL atılır, ardından ikinci numune tüplere alınır. Kan gazı için kan heparinli kapiller tüpe alınır ve hava teması önlenir (hava CO2 düzeyini etkiler). Kateter bakımı aseptik teknikle yapılmalı, lümendeki heparinli sıvı kullanılacaktır." },

/* ---------------- ENFEKSİYON & İZOLASYON ---------------- */
{ t:"bilgi", k:"enfeksiyon", z:2,
  s:"El hijyeninin 5 endikasyonu nelerdir?",
  o:["Sadece yılda birkaç kez","Hastaya dokunmadan önce, temastan sonra, vücut sıvısı riski sonrası, hasta çevresine dokunmadan önce ve sonra",
     "Yalnızca eldiven giymeden önce","Hastanın odasına girmeden önce"], d:1,
  a:"El hijyeni 5 endikasyon: hastaya dokunmadan önce, temastan veya istile dokunduktan sonra, vücut sıvısı ile temastan sonra, hastanın çevresine dokunmadan önce ve hastanın çevresine dokunduktan sonra. Alkol bazlı el antiseptiği görünür kirlilik yoksa 20-30 saniye uygulanır; eldiven kullanıldıysa eldiven çıkarıldıktan hemen sonra da el hijyeni yapılır." },

{ t:"bilgi", k:"enfeksiyon", z:2,
  s:"Damlacık yoluyla bulaşan enfeksiyonda (örneğin influenza) uygulanacak izolasyon nedir?",
  o:["Yalnızca eldiven ve önlük yeterlidir",
     "Hasta ve sağlık çalışanı maske takar, damlacık oluşturan işlemlerde damlacık önlüğü kullanılır, hastanın yüzüne 1 metreden yaklaşılmaz",
     "Negatif basınçlı oda","Tamamen kapalı sistem ve nakil gerekir"], d:1,
  a:"Damlacık izolasyonunda hasta ve sağlık çalışanı maske takar, damlacık oluşturabilecek işlemlerde (öksürme, yutma, vokal kord) damlacık önlüğü kullanılır, hastanın yüzüne 1 metreden yaklaşılmaz ve odada maskesiz personel bulundurulmaz. Tedavi başladıktan 48 saat sonra (Pnömokok için 24 saat, MRSA için kültür negatifleşene kadar) önlemler kaldırılabilir." },

{ t:"bilgi", k:"enfeksiyon", z:2,
  s:"Hepatit B veya HIV ile temas sonrası keskin alet yaralanmasında ilk müdahale nedir?",
  o:["Yarayı sıkı kapat, bir hafta sonra kontrol et",
     "Kan kaynağa doğru sıkma, 5 dakika boyunca akan su altında yıkama, sonra derhal enfeksiyon kontrolüne bildirme",
     "Sadece antibiyotik başla","Bekle ve izle"], d:1,
  a:"Kesici tırtıklı aletle çalışırken kan kaynağa doğru sıkılır (uzaklaşmayı engelleyecek şekilde) ve 5 dakika boyunca akan su altında yıkanır; mukoza teması varsa bol su ile yıkanır. Sonra meslek sağlığı ve enfeksiyon kontrolüne acil bildirim yapılır: hepatit B için aşı ve immünoglobulin, HCV için takip, HIV için 1-2 saat içinde profilaksi başlanması kritik önem taşır." },

{ t:"bilgi", k:"enfeksiyon", z:2,
  s:"MRSA kontrolünde en etkili yaklaşım nedir?",
  o:["Her hastaya rutin antibiyotik vermek",
     "Sık el hijyeni, çevre temizliği, MRSA taraması, temas izolasyonu ve klorheksidin ile dekontaminasyon",
     "UV ışık uygulamak","Hastaları aynı odada toplamak"], d:1,
  a:"MRSA kontrolünün temeli sıkı el hijyeni, çevre temizliği ve temas izolasyonudur. Giriş izolasyonu gereken hastalarda klorheksidin veya duaklorheksidin ile günlük dekontaminasyon, MRSA taraması ve kültür temizliği sonrası izolasyonun kaldırılması uygulanır. UV robotları destekleyici olarak kullanılabilir ancak tek başına yeterli değildir." },

{ t:"bilgi", k:"enfeksiyon", z:3,
  s:"Titreme, 39 derece ateş, taşikardi ve hipotansiyon varsa sepsis şüphesinde ilk 1 saatte ne yapılır?",
  o:["Antibiyotiği 4 saat beklet",
     "Antimikrobiyal öncesi kan kültürü al, 30 mL/kg kristaloid ile sıvı resüsitasyonu başlat, erken empirik antibiyotik ver, laktat ölç",
     "Sadece parasetamol ver","Hastayı yatır ve izle"], d:1,
  a:"Sepsiste hayat kurtaran Saat-1 paketi: 1 saat içinde kan kültürü (antimikrobiyal öncesi), IV erişim, 30 mL/kg kristaloid, ortalama arter basıncını 65 mmHg üzerine çıkarmak için sıvı veya vazopressör, laktat ölçümü ve tekrarlanması, uygun kapsamlı empirik antimikrobiyal. Gecikmiş antibiyotik her saat mortaliteyi artırır. Kaynak kontrolü (drenaj, debridman) ihmal edilmemelidir." },

/* ---------------- FARMAKOLOJİ ---------------- */
{ t:"bilgi", k:"farmako", z:2,
  s:"İnsülin hangi gruptandır ve kan şekerini nasıl düşürür?",
  o:["Antikoagülan; pıhtılaşmayı azaltır",
     "Antidiyabetik; glukozun hücreye alınmasını artırır, glukoneogenezi ve glikogenolizi baskılar",
     "Kortikosteroid; inflamasyonu baskılar","Antibiyotik; bakterileri öldürür"], d:1,
  a:"İnsülinler iki gruptur: hızlı etkili (regular, lispro, aspart) ve uzun etkili (NPH, glarjin, detemir). Kan şekerini düşürmek için hücresel glukoz alımını artırır, glukoneogenezi ve glikogenolizi inhibe eder, glikojen sentezini uyarır ve lipolizi azaltır. Yanlış dozda ölümcül hipoglisemi, aşırı dozda ketoasidoz gelişebilir." },

{ t:"bilgi", k:"farmako", z:3,
  s:"Digoksin kullanan hastanın nabzı 56/dk tespit edildi. Ne yapılmalı?",
  o:["İlacı aynen devam ettir",
     "İlacı durdur, hekime bildir, EKG ve serum digoksin düzeyi iste, potasyum ve diüretik kullanımını değerlendir",
     "İlacı iki kat artır","Yeni doz verip izlemeye devam et"], d:1,
  a:"Digoksinin tedavi penceresi dardır. Nabız 60/dk altında veya düzensizse ilaç aritmi ve dijital intoksikasyon riskini artırır. İntoksikasyon bulguları: iştahsızlık, bulantı-kusma, sarı-yeşil görme, nörolojik bulgular. Hipokalemi toksikliği artırır. Tedaviye ara verilir, EKG ve serum düzeyi istenir, doktora derhal bildirilir." },

{ t:"bilgi", k:"farmako", z:2,
  s:"Opioidlerin en tehlikeli yan etkisi ve antidotu nedir?",
  o:["Bulantı - metoklopramid","Solunum depresyonu - nalokson","Uykululuk - kafein","Kabızlık - senna"], d:1,
  a:"Opioidlerin en tehlikeli etkisi solunum depresyonudur. Aşırı dozda CO2 duyarlılığı artar, Cheyne-Stokes solunumu, apne ve arrest gelişebilir. Antidotu naloksondur (0,4-2 mg IV; hastaya verilen ilacın yarı ömrüne bağlı olarak tekrarlanabilir veya infüzyon gerekebilir). Solunum sayısı ve bilinç düzeyi izlemi zorunludur." },

{ t:"bilgi", k:"farmako", z:2,
  s:"Anafilazide adrenalin (Epipen) nasıl uygulanır?",
  o:["İntraven yavaş infüzyon",
     "Dış kısmıyla dikey olarak uyluk dış kasın içine, hızlı, yaklaşık 5 cm derinlikte, 0,3 mg (erişkin)",
     "Subkutan olarak kola","İntramusküler olarak omuzüstü"], d:1,
  a:"Adrenalin anafilakside birinci basamak ve hayat kurtarıcı tedavidir; gecikme en büyük ölüm nedenidir. Uygulama: intramusküler, uyluk dış-yan tarafı, dikey, yaklaşık 5 cm derinlikte. 5 dakika içinde yanıt gelmezse doz tekrarlanır. IV yol uzman kullanım içindir. Birlikte oksijen, sıvı ve gerekirse antihistaminik ile kortikosteroid verilir; hasta gözlem altında tutulur." },

{ t:"bilgi", k:"farmako", z:2,
  s:"Antikoagülan ve antiagregan ilaçların en tehlikeli ve en tipik yan etkisi nedir?",
  o:["Hepatotoksisite","Kanama (gastrointestinal, intrakranial)","Hiperglisemi","Ototoksisite"], d:1,
  a:"Kanama en tehlikeli etkidir; gastrointestinal kanama en sık, intrakranial kanama en ağırdır. Hemşirelik bakımı: vital bulgular, melena ve hematemezi, idrarda kan, göz çevresi ekimozu takibi; kanama riski varsa yumuşak diş fırçası, ustura kullanmama, düşmeye karşı önlem, ilaç-antidot bilgisi (varfarin: vitamin K ve protrombin kompleksi; heparin: protamin sülfat). Uzun süreli NSAİI kullanımı ayrıca GI kanama riskini artırır." },

{ t:"bilgi", k:"farmako", z:2,
  s:"Açıklama ilaçları (NSAİI) ne zaman ve nasıl verilmelidir?",
  o:["Yemekle birlikte her zaman","Aç karnına, yemekten en az 30 dakika önce veya 2 saat sonra, yeterli su ile",
     "Yatmadan önce mutlaka","Tok karnına, suyla değil"], d:1,
  a:"NSAİIler (ibuprofen, diklofenak, naproksen) aç karnına alınmalıdır: yemekten en az 30 dakika önce veya 2 saat sonra, yeterli su ile. Yemekle birlikte alınması mide irritasyonunu ve GI kanama riskini artırır. Özellikle yaşlı, böbrek yetmezliği ve peptik ülser öyküsü olan hastalarda dikkat gerekir." },

/* ---------------- ENDOKRİN & DİYABET ---------------- */
{ t:"bilgi", k:"endokrin", z:2,
  s:"Diyabette hipoglisemi (kan şekeri düşüklüğü) sınırı kaç mg/dL'dir?",
  o:["70 altı","100 altı","130 altı","200 altı"], d:0,
  a:"Hipoglisemi kan şekeri 70 mg/dL altıdır. Belirtiler: terleme, titreme, açlık, çarpıntı, sinirlilik, bulanık görme, konfüzyon. Tedavi: bilinç yerindeyse 15 g hızlı karbonhidrat (4-6 küp şeker, meyve suyu), 15 dakika sonra tekrar ölç, gerekirse tekrarla. Bilinç bozuksa ağızdan bir şey verilmez; glukagon uygulanır ve hasta acil servise alınır." },

{ t:"bilgi", k:"endokrin", z:3,
  s:"Diyabetik ketoasidozda hastanın solunumu nasıl karakterizedir?",
  o:["Cheyne-Stokes solunumu","Kussmaul solunumu: derin, hızlı, ağır; aseton kokusu ve dehidrasyon",
     "Solunum sayısı azalır, apne gelişir","Bazal metabolik hızda solunum"], d:1,
  a:"DKA'da keton üretimi artar (aseton kokusu), metabolik asidoz derinleşir ve solunum merkezi Kussmaul solunumu ile telafi eder: derin, hızlı ve ağır. Diğer bulgular: dehidrasyon, poliüri, kusma, karın ağrısı, ketonüri ve asidotik kan gazı. Tedavi: öncelikli IV sıvı, insülin infüzyonu, potasyum takibi; bikarbonat yalnızca pH 6,9 altında düşünülür." },

{ t:"bilgi", k:"endokrin", z:2,
  s:"HbA1c neyi gösterir ve genel hedef nedir?",
  o:["Anlık kan şekeri; hedef 80-110 mg/dL",
     "Son 2-3 ayın ortalama glisemik kontrolü; genel hedef yüzde 7 civarı",
     "İnsülin miktarı; hedef 0,5-1 ünite/kg","Keton düzeyi; hedef negatif"], d:1,
  a:"HbA1c, gliklize hemoglobinin son 2-3 ay içindeki ortalama oranını yansıtır ve kronik glisemik kontrolün en güvenilir göstergesidir. Hedef bireyselleştirilir: çoğu yetişkinde yüzde 7 altı, yaşlı ve uzun süreli hastada yüzde 8 altı, genç ve kısa süreli diyabette yüzde 6,5 kabul edilebilir. Gebelikte hedef daha sıkıdır. HbA1c anlık hipoglisemiyi göstermez." },

{ t:"bilgi", k:"endokrin", z:2,
  s:"Uzun süreli diyabette ayak bakımı için hangisi YANLIŞTIR?",
  o:["Her gün yumuşak sabunla yıkama, ılık su, parmak araları kurutulmalı",
     "Sıcak suyla çorba veya ısıtıcı kullanmak",
     "Düzenli ayak muayenesi ve uygun ayakkabı kullanımı",
     "Sıcak suyu dirsek veya termometre ile kontrol etmek"], d:1,
  a:"Diyabette çorba, ısıtıcı, sıcak kum veya doğrudan ısı kaynağı kullanmak, diyabetik nöropidi nedeniyle ısı hissi kaybı yaşayan hastalarda ciddi yanık riski taşır ve yasaktır. Bakımın temel taşları: günlük yıkama ve parmak arası kurutma, tırnağın makasla düzeltilmesi (makasla kesme), ayakkabı değerlendirmesi, yara muayenesi ve düzenli egzersiz." },

/* ---------------- CERRAHİ BAKIM ---------------- */
{ t:"bilgi", k:"cerrahi", z:2,
  s:"Ameliyat sonrası erken mobilizasyonun temel amacı nedir?",
  o:["Yaranın daha çabuk iyileşmesi",
     "Atelektazi, pnömoni, derin ven trombozu, bası yarası ve ileus riskini azaltmak",
     "Ağrıyı kesmek","Yatakta kalış süresini uzatmak"], d:1,
  a:"Erken mobilizasyon postoperatif bakımın temel taşıdır: akciğer ekspansiyonunu artırarak atelektazi ve pnömoniyi, kas kaybını, DVT riskini, bası yaralarını ve bağırsak atonisini azaltır. Anestezi sonrası ilk saatlerde yataktan kalkma, derin solunum ve öksürme egzersizleri, bacak egzersizleri planlanır. Ağrı kontrolü mobilizasyonun ön koşuludur." },

{ t:"bilgi", k:"cerrahi", z:2,
  s:"Yara enfeksiyonunun klasik 5 kırtırtı (SIRS) bulgusu hangisidir?",
  o:["Ateş, titreme, lökositoz, taşikardi, hipotansiyon",
     "Kızarıklık, sıcaklık, şişlik, ağrı, hassasiyet",
     "Bulantı, kusma, iştahsızlık, yorgunluk, kilo kaybı",
     "Dispne, taşipne, hipoksi, siyanoz"], d:1,
  a:"Erken yara enfeksiyonunun lokal bulguları: rubor (kızarıklık), kalor (sıcaklık), tumor (şişlik), dolor (ağrı), functio laesa (fonksiyon kaybı). Ateş, lökositoz, CRP artışı, pürülan drenaj ve yara ayrışması sistemik enfeksiyonu gösterir. En sık etkenler Staphylococcus aureus ve Enterokok türleridir; tedavi kültür sonucuna göre başlamalıdır. Yara bakımında eldiven ve aseptik teknik zorunludur." },

{ t:"bilgi", k:"cerrahi", z:2,
  s:"Nazogastrik tüpün doğru yerleştiğinin en güvenilir doğrulama yöntemi nedir?",
  o:["Hastaya su içirip öksürtmek","Göğüs grafisi (röntgen) ile doğrulama; pH kontrolü tarama amaçlıdır",
     "Tüpü 10 cm daha ilerletmek","Hastaya yutabilir misin diye sormak"], d:1,
  a:"NG tüpün konumu mutlaka göğüs grafisi ile doğrulanır; aspiratın pH kontrolü (pH 5,5 altı) tarama amaçlıdır ancak tek başına yeterli değildir. Tespit edilen olayların çoğu göğüs boşluğuna, akciğere veya kafaya yerleşmedir. Yerleştirme sonrası tüpü sabitleme, cm olarak işaretleme, dışarı kaymasını önleme, ağız bakımı ve yeterli sıvı alımının sağlanması hemşirelik sorumluluğundadır." },

{ t:"bilgi", k:"cerrahi", z:3,
  s:"Cerrahi profilaktik antibiyotik ne zaman ve nasıl uygulanmalıdır?",
  o:["Ameliyattan 1-2 saat önce, tek doz IV, bitimden 60-120 dakika sonra kesilerek",
     "Ameliyat öncesi sabah oral alınarak","Ameliyat boyunca her saat tekrarlanarak",
     "Ameliyattan 1 gün önce başlayıp 5 gün sürdürülerek"], d:0,
  a:"Cerrahi profilaksi insizyondan en geç 60 dakika önce (klindamycin veya vankomisin gibi ilaçlarda 120 dakika önce) IV olarak verilir. Düşük doz veya yetersiz doz direnç riskini artırır. Ameliyat bittikten sonra profilaktik doz tekrarlanmaz ve en geç 60-120 dakika içinde durdurulur. Cerrahi kirlilik derecesine göre 24 saatten uzun profilaksi önerilmez." },

/* ---------------- KAN TRANSFÜZYONU ---------------- */
{ t:"bilgi", k:"kan", z:3,
  s:"Kan transfüzyonunda doğru hasta ve doğru kan kontrolü nasıl yapılır?",
  o:["Hastanın bileğindeki kan grubu yeterlidir",
     "En az iki sağlık çalışanı, kan ünitesindeki etiket ile hastanın kimlik bileziğini ve kan grubu sonucunu birlikte kontrol eder",
     "Doktorun istemi yeterlidir","Aile reaksiyonuna bakılır"], d:1,
  a:"Transfüzyon öncesi hasta kimlik doğrulaması en az iki sağlık çalışanı tarafından yapılır: kan ünitesindeki etiket ile kimlik bileziği ve kan grubu sonucu karşılaştırılır. Transfüzyon seti, damar yolu (tercihen periferik, orta veya büyük bir kateter), vital bulgular ve reaksiyon gözlemi için kaşe ve yakın takip planlanır. İlk 15 dakika yavaş akıtılır ve hasta gözlenir." },

{ t:"bilgi", k:"kan", z:3,
  s:"Transfüzyon sırasında titreme, ateş, sırt ağrısı, göğüs ağrısı ve kırmızı idrar gelişirse ilk müdahale nedir?",
  o:["Transfüzyonu hızlandırmak","Transfüzyonu hemen durdurmak, seti çıkarmak, damarı serum fizyolojik ile yıkamak, kan kültürü ve idrar örneği almak, hekime ve kan bankasına bildirmek",
     "Antipiretik verip devam etmek","Sadece yavaşlatmak"], d:1,
  a:"Akut transfüzyon reaksiyonu hayatı tehdit edicidir. İlk adım transfüzyonu durdurmak ve damarı serum fizyolojik ile yıkamaktır (böbrek hasarını azaltır). Kan kültürü ve idrar örneği alınır, hekime ve kan bankasına derhal haber verilir, kan seti etiketi ve ilaç kayıtları saklanır. Belirtiye göre antihistaminik, adrenalin, furosemid ve yoğun bakım gerekebilir." },

{ t:"bilgi", k:"kan", z:3,
  s:"Erişkinde 1 ünite eritrosit (yaklaşık 450 ml) transfüzyonunda beklenen hemoglobin artışı nedir?",
  o:["1 g/dL","3 g/dL","7 g/dL","10 g/dL"], d:1,
  a:"1 ünite eritrosit eritrosit kütlesini 10 mL/kg artırır ve erişkinde hemoglobinı yaklaşık 1 g/dL, hematokriti yaklaşık yüzde 3 artırır. Bu nedenle transfüzyon sonrası hemoglobin kontrolü yapılır. Transfüzyon endikasyonu: stabil hastada Hb 7 g/dL altı, kardiyovasküler hastalık riski taşıyanlarda 8 g/dL altı." },

/* ---------------- ÇOCUK SAĞLIĞI ---------------- */
{ t:"bilgi", k:"cocuk", z:2,
  s:"APGAR skoru ne zaman ve nasıl hesaplanır?",
  o:["Doğumdan 1. ve 5. dakikada; görünüm, nabız, yüz ifadesi, aktivite, solunum. Her bir 0-2 puan, toplam 10",
     "Doğumdan 1. saatte, boy-kilo ölçümüyle","Doğumdan 10. dakikada, tam muayeneyle",
     "Doğumdan 1-3-5-10. dakikalarda kan gazıyla"], d:0,
  a:"APGAR doğumun 1. ve 5. dakikasında hesaplanır, gerekirse 10. dakikada tekrarlanır. Bileşenler: Appearance (görünüm), Pulse (nabız), Grimace (yüz ifadesi), Activity (kas tonu), Respiration (solunum çabışması). Her biri 0-2 puan, toplam 10 üzeri. 0-3 acil resüsitasyon, 4-6 destekleyici bakım, 7-10 gözlem. 5. dakikadaki skor 1. dakikadan daha anlamlıdır." },

{ t:"bilgi", k:"cocuk", z:2,
  s:"Yenidoğanda hangi kan gazı değerleri fizyolojik olarak normal kabul edilir?",
  o:["pH 7,35-7,45 ve PaCO2 35-45","pH 7,25-7,40 ve PaCO2 30-35","pH 7,50-7,60","pH 7,10-7,20"], d:1,
  a:"Doğumda fetüsün fizyolojik hipoksi nedeniyle PaCO2 yüksektir. Doğumu takiben ilk 1-2 saatte CO2 hızla düşer ve arteriyel pH yükselir. Bu nedenle yenidoğanda 1. gün pH 7,25-7,40 ve PaCO2 30-35 aralığı fizyolojik olarak normal kabul edilir. Yorum yaparken saatler ve kapiller ile arteriyel ölçüm arasındaki fark göz önünde bulundurulmalıdır." },

{ t:"bilgi", k:"cocuk", z:2,
  s:"Yenidoğanın doğum sonrası ısıtılmasında doğru yaklaşım nedir?",
  o:["Sıcak suyla yıkanarak hızlı ısıtılır",
     "Kuru, termistörlü radyant ısıtıcı altında doğrudan ısıtılır; ıslak ve nemli çevreden uzak tutulur",
     "Battaniyeye sarılması yeterlidir","Kucağa alınması yeterlidir"], d:1,
  a:"Isı kaybı yüzey alanı / kütle oranına bağlıdır; yenidoğanda göreceli olarak çok yüksektir. Bu nedenle doğumdan sonraki ilk saat altın saattir: ısı kaybının en aza indirilmesi (termistörlü radyant ısıtıcı), ıslak çevreden ayrılma, başın ve gövdenin ısıtılması, kanguru anne bakımı, sıcak yüzde bakım. Hipotermi (36,5 altı) hipoglisemi ve metabolik sorunlara yol açar." },

{ t:"bilgi", k:"cocuk", z:3,
  s:"Çocuklarda dehidratasyonun en erken klinik bulguları nelerdir?",
  o:["Gözyaşı kuruması, mukozal kuruluk, idrar miktarının azalması ve kapiller dolum süresinin uzaması",
     "Vücut ağırlığı kaybı yüzde 10'u geçmeden bulgu vermez","Ateş","Bulantı ve kusma"], d:0,
  a:"Çocuklarda total vücut suyu oranı yaşla azalır: infantta yüzde 70-80, erişkinde yüzde 60. Bu nedenle çocuklar daha hızlı su kaybeder ve klinik bulgu geç ortaya çıkar. Erken belirtiler: mukozal kuruluk, gözyaşı azalması, idrar miktarı ve sıklığının azalması, kapiller dolum süresinin uzaması, letarji. Vücut ağırlığı en güvenilir göstergedir: yüzde 5-10 orta, yüzde 10 üzeri şiddetli kayıp." },

{ t:"bilgi", k:"cocuk", z:3,
  s:"Oral rehidratasyon solüsyonunda (ORS) tuz ve glikozun birlikte bulunma amacı nedir?",
  o:["Tadı iyileştirmek",
     "Sodyumun ve glikozun bağırsak lümeninden birlikte emilimini sağlayarak net sıvı ve elektrolit dengesini korumak",
     "Bağırsak hareketlerini yavaşlatmak","İştahı artırmak"], d:1,
  a:"ORS'da glikoz ve sodyum, bağırsak lümeninde birlikte emilir (SGLT1 kotransporter aracılığıyla); bu da su emilimini kolaylaştırır. Bu nedenle tuz ve şeker birlikte verilir. Aşırı yoğun ev yapımı solüsyonlar (özellikle tuz fazlası) hipernatremiye yol açabilir. Hafif-orta dehidrasyonda ORS ana tedavidir; meşrubat ve meyve suyu gibi içecekler elektrolit dengesini bozar." },

/* ---------------- KADIN DOĞUM ---------------- */
{ t:"bilgi", k:"dogum", z:2,
  s:"Normal term gebeliğin süresi nedir ve Naegele kuralına göre tahmini doğum tarihi nasıl hesaplanır?",
  o:["9 ay; son adet tarihine gün eklenerek bulunur",
     "40 hafta (280 gün); son adet tarihinin ilk günü + 7 gün, sonra 3 ay geri",
     "38 hafta; son adet tarihinden 3 hafta çıkarılır","42 hafta; tahmin edilemez"], d:1,
  a:"Normal gebelik süresi son adet tarihinin ilk gününden itibaren 280 gün (40 hafta) kabul edilir. Naegele kuralı: tahmini doğum tarihi = son adet tarihinin ilk günü + 7 gün, sonra 3 ay geri. 280 günden önce doğum erken, sonrası geç sayılır. Uterus fundusunun symphysis pubis mesafesi ileri haftalarda destekleyici bilgi verir." },

{ t:"bilgi", k:"dogum", z:3,
  s:"Preeklampsi tablosunun en karakteristik bulgusu nedir?",
  o:["Tek taraflı baş ağrısı ve karın ağrısı",
     "20. gebelik haftasından sonra gelişen yeni hipertansiyon ve proteinüri veya end-organ tutulumu",
     "Hiperemezis ve kilo kaybı","Polihidramnios"], d:1,
  a:"Preeklampsi: 20. haftadan sonra yeni başlangıçlı hipertansiyon (140/90 ve üzeri) ve proteinüri (300 mg/24 saat veya 1+) ya da end-organ tutulumu (nörolojik bulgular, görme bozukluğu, karaciğer enzim yükselmesi, trombositopeni, akciğer ödemi, oligüri). Tedavi: magnezyum sülfat (nöroproksiyon ve antikonvülsan), hipertansiyon kontrolü, sık vital ve laboratuvar takibi, acil doğum planlaması. HELLP sendromu (hemoliz, yükselmiş karaciğer enzimleri, düşük trombosit) acil bir tablo." },

{ t:"bilgi", k:"dogum", z:2,
  s:"Doğumdan sonra ilk saatte emzirme için en önemli girişim nedir?",
  o:["Bebeği tartmak",
     "Bebeği annenin göğsüne cilt-cilde temasla, doğumdan sonraki ilk 1 saat içinde emzirmeye başlatmak ve desteklemek",
     "Bebeği ısıtıcıya yerleştirmek","Bebeğe mama vermek"], d:1,
  a:"Anne ve bebeğin doğumdan sonraki ilk 1 saat içinde cilt-cilde teması ve erken emzirme; emzirme başarısını, kolostrum alımını, uterinvolüsyonu ve süt üretimini olumlu etkiler, ağırlık kaybını azaltır. Emzirmede doğru pozisyon ve iyi latch (kilitlenme) esastır: bebeğin burnu memeye bakmalı, karın annenin karnına temas etmeli. Sık uyanma ve her 2-3 saatte bir beslenme önerilir." },

{ t:"bilgi", k:"dogum", z:3,
  s:"Doğum sonrası normal loşi özellikleri ve takibi nedir?",
  o:["İlk günlerde keskin, keskin kokulu ve her gün artan kanama",
     "İlk 1-3 gün kırmızı, sonra sero-hemorajik, 6. gün civarında beyaz, haftalar içinde azalarak sürer; kanama miktarı ve uterus tonusu takip edilir",
     "Hepsi aynı renkte ve miktarda olmalıdır","24 saatten sonra hiç kanama olmamalıdır"], d:1,
  a:"Normal loşi (kötü): 1-3 gün kırmızı, 4-6. gün sero-hemorajik (pembe-kahve), 7-10. gün beyaz-gri, 3-6 haftaya kadar sürer. Kanama miktarı (ped sayısı, saatlik), pihtı, koku, uterus tonusu, vital bulgular ve enfeksiyon bulguları takip edilir. Kanamanın aniden artması ve yumuşak uterus uterin atoniyi düşündürür; oksitosik ve uterin masaj ile müdahale gerekir." },

/* ---------------- İLK YARDIM & CPR ---------------- */
{ t:"bilgi", k:"ilkyardim", z:2,
  s:"Bilinc kapalı hastada temel yaşam desteği öncelik sırası nedir?",
  o:["Hava yolu açma ve solunum desteği, 5 kurtarıcı canlı arama, CPR başlatma, AED uygulama, 112 arama",
     "Yalnızca ısıtmak","Su yudumlatmak","Hastayı yürütmek"], d:0,
  a:"Öncelik sırası: 1) Hava yolu açma ve solunum desteği (varsa hastanın kendi solunumu desteklenir, yoksa balon-maske), 2) CPR başlatma, 3) AED var en kısa sürede uygulanması, 4) 112 aranarak acil tıbbi yardım istenmesi. Su içirme, ısıtıcı uygulama ve yürüme uygun değildir; ağır hipotermide kurtarma süresince hastanın ölü olmadığı ilkesi geçerlidir." },

{ t:"bilgi", k:"ilkyardim", z:2,
  s:"Termal (sıcak) yanıkta ilk müdahale nedir?",
  o:["Buz doğrudan uygulanır",
     "Yanan bölge 10-20 dakika ılık akan su altında tutulur; takma ve üstüne krem sürülmez, soğuk veya buz uygulanmaz, 112 aranır",
     "Bölge yağlanır","Bülge patlatılır"], d:1,
  a:"Termal yanıkta 10-20 dakika ılık su altında soğutma termal hasarı sınırlar. Takma ve üstünü örtme uygundur; krem, yağ, terebentin, buzdolabı, yağ, patates gibi uygulamalar yapılmaz. Bülge kendiliğinden patlatılmaz. Yüz, el, ayak, geniş yüzey, eklem ve kimyasal ya da elektrik yanıklarında mutlaka sağlık kuruluşuna başvurulur; ciddi yanıkta 112 aranır." },

{ t:"bilgi", k:"ilkyardim", z:2,
  s:"Ekstansiyon kanama ve gömülü kırıkta doğru yaklaşım nedir?",
  o:["Kanama bölgesine bastır, sıkı destekli bandaj uygula, kırığı mevcut haliyle destekle, hastayı hareket ettirmeden 112 ara",
     "Kırık kemiği yerine oturt","Bastırmayı bırak, kanamanın kendiliğinden durmasını bekle",
     "Sadece ağrı kesici ver, başka dokunma"], d:0,
  a:"Ekstansiyon kanamada doğrudan baskı ve kanama kontrolü sağlandıktan sonra sıkı destekli bandaj uygulanır. Kanlı ıslak gazlı bez değiştirilmez, üzerine eklenir. Gömülü kırıkta kemik asla yerine oturtulmaz, yalnızca mevcut haliyle desteklenir (at immobilizasyonu, kol askısı). Bacak kırıklarında kanama olsa bile boşluk atı ile destekleme ısı kaybını önler." },

{ t:"bilgi", k:"ilkyardim", z:3,
  s:"AED (otomatik ekstern defibrilatör) hangi durumda kullanılır?",
  o:["Herkes için, isteğe bağlı","Bilinçsiz ve normal solunumu olmayan hastada (nabzı olup olmadığına bakılmaksızın); 8 yaş üstünde erişkin pedi, küçük çocukta pediatrik ped varsa onun kullanılması",
     "Yalnızca yaşlı hastalarda","Yalnızca nabzı varsa"], d:1,
  a:"AED, bilinçsiz ve normal solunumu olmayan (agonal solunum sayılmaz) her yaştaki hasta için kullanılır. Cihaz ritmi analiz eder ve şoklanabilir aritmi (ventriküler fibrilasyon, nabızsız ventriküler taşimani) saptarsa şok verir; şoklamazsa CPR'a devam etmek için komut verir. Pediatrik ped 8 yaş altı çocuklar ve 25 kg altı için, yoksa erişkin pedi kullanılır." },

/* ---------------- HASTA GÜVENLİĞİ ---------------- */
{ t:"bilgi", k:"guvenlik", z:2,
  s:"Doğru hasta, doğru işlem ilkesinde hasta kimlik doğrulaması nasıl yapılır?",
  o:["Sadece isim sorularak",
     "En az iki kimlik bilgisi (ad soyad, doğum tarihi) iki bağımsız kaynaktan (bilezik ve dosya veya barkod) eşleştirilir; gerekirse hastaya sorularak doğrulanır",
     "Bilek bandı yeterlidir","Odaya girerken isim seslenmesi yeterlidir"], d:1,
  a:"Hastayı doğru tanımlamak için en az iki kimlik doğrulayıcı (ad, soyad, doğum tarihi, protokol numarası) iki bağımsız kaynaktan (bilezik, dosya, barkod) karşılaştırılır. En güvenilir yöntem hastaya açık uçlu soru sormaktır (örneğin doğum tarihi). Kan, ilaç, gıda, transplant ürünleri ve tüm invaziv işlemlerde bu kontrol zorunludur." },

{ t:"bilgi", k:"guvenlik", z:2,
  s:"İlaç güvenliğinde doğru ilaç, doğru doz, doğru yol, doğru zaman, doğru hasta ilkesinin doğru yol bileşeni ne demektir?",
  o:["İlacın uygun olduğu hastaya verilmesi",
     "İlacın tamamının doğru, güncel ve okunabilir talimatla yazılı ve sözlü olarak soru sorarak (read-back) uygulanması",
     "En ucuz ilacın seçilmesi","Reçeteyi yazan hekim olması"], d:1,
  a:"Doğru yol: uygulama öncesi ilacın adının, dozunun, yolunun ve zamanının yazılı talimattan ve soru sorularak (read-back) doğrulanması; hazırlanan ve doğrulanmış ilaçların birbirinden ayrılması; benzer isimli ve benzer ambalajlı ilaçların ayrı depolanması; uyarı etiketleri, barkod ve akıllı pompa kullanımı. Tüm ilaçlar tek kişiden geçer, ikinci kontrol yapılır ve kayıt tutulur." },

{ t:"bilgi", k:"guvenlik", z:3,
  s:"Bası yaralarını önlemede en etkili yaklaşım nedir?",
  o:["Bası yarası oluşunca maste yapmak",
     "Risk değerlendirmesi (Braden ölçeği), düzenli pozisyon değişimi, bası azaltıcı yüzey, yeterli protein ve sıvı, cilt bakımı, erken fark etme",
     "Sadece yatağa maste yapmak","Hastayı hareketsiz bırakmak"], d:1,
  a:"Bası yarası çoğunlukla önlenebilir bir komplikasyondur. Risk değerlendirmesi (Braden skoru: duyusal, nemlenme, aktivite, hareketlilik, beslenme, vücut ağırlığı), 2 saatte bir pozisyon değişimi (30 derece lateral tilt, topuk yastıkları ile topuktan yük alma), bası azaltıcı yüzeyler, cilt bakımı, yeterli protein ve enerji alımı, idrar ve fekal kaçak yönetimi, aile eğitimi esastır. Oluşmuş yarada bası azaltma, beslenme ve yara bakımı birlikte planlanır." },

{ t:"bilgi", k:"guvenlik", z:2,
  s:"İlaç hatası (near miss dahil) fark edildiğinde ilk yapılacak nedir?",
  o:["Kimseye söylememek, üstü örtmek","Hastayı değerlendirip gerekli müdahaleyi yapmak, hekime ve sorumlu hemşireye derhal bildirmek, olay kaydı ve kök neden analizi başlatmak",
     "Hastanın yakınlarına bildirmek ve beklemek","Hastayı başka servise taşımak"], d:1,
  a:"İlaç hatası veya ramak kala (near miss) olayında önce hasta güvenliği: hasta değerlendirilir, antidot ve gerekli müdahale uygulanır, sorumlu hekime ve hemşireye derhal bildirilir. Ardından ilaç kayıtları, order ve uygulama kayıtları saklanır, bildirim (olay raporu) yapılır ve kök neden analizi (neden oluş, neden yakalanmadı) ile sisteme dönük düzeltici faaliyetler planlanır. Suçlayıcı, cezalandırıcı kültür güvenliği azaltır." }
];

/* =====================================================================
   TERİM - TANIM EŞLEŞTİRME
   ===================================================================== */
const TERIMLER = [
  ["Anemi", "Hemoglobin düşüklüğü nedeniyle dokulara oksijen taşıma kapasitesinin azalması"],
  ["Nekroz", "Hücre ölümü ve doku tahribatı"],
  ["Ödem", "Doku aralığında sıvı birikmesi"],
  ["Atresi", "Doğuştan bir organ veya kanalın kapalı olması"],
  ["Metastaz", "Primer tümörün uzak organlara yayılması"],
  ["Dispne", "Nefes darlığı hissi"],
  ["Aritmi", "Kalp ritminin düzensiz olması"],
  ["Letarji", "Tükenmişlik, uyuşukluk, tepkide gecikme"],
  ["Hipertansiyon", "Kan basıncının tekrarlayan olarak yükselmesi"],
  ["Epilepsi", "Tekrarlayan bilinç kaybı veya konvülsiyonla seyreden nöbet bozukluğu"],
  ["Koma", "Ağrılı uyaran dahil hiçbir uyarana yanıt vermeme"],
  ["Hipotansiyon", "Düşük kan basıncı"],
  ["İnkontinans", "İdrar veya dışkı kontrol kaybı"],
  ["Apne", "Geçici solunum durması"],
  ["Hiperemezis", "Gebelikte aşırı kusma ve dehidrasyon"],
  ["Sepsis", "Enfeksiyona bağlı hayat organı işlev bozukluğu"],
  ["Koagülopati", "Pıhtılaşma sistemi bozukluğu"],
  ["Ekspirasyon", "Solunumla havanın akciğerden dışarı çıkması"],
  ["Flatus", "Bağırsaklardan atılan gaz"],
  ["Parenteral", "Sindirim sistemi dışından uygulanan"],
  ["İnkübasyon", "Bulaşıcı etkenin çoğalma veya kuluçka süresi"],
  ["Dekubitus", "Bası yarası"],
  ["Suction", "Emme işlemi"],
  ["Trombosit", "Kan pıhtılaşmasında görevli kan hücresi"],
  ["Kardiyak output", "Kalbin bir dakikada pompaladığı kan miktarı"],
  ["Defisit", "Eksiklik, açık (örneğin oksijen defisiti)"],
  ["Anafilaksi", "Ani, hayatı tehdit eden alerjik reaksiyon"],
  ["Pnömoni", "Akciğer dokusunun enfeksiyonu"],
  ["Sepsis şoku", "Sepsiste vazopressör ve laktat artışı ile hipotansiyon"],
  ["İnkübatör", "Yenidoğanı bakım için ısıtılan, kontrollü ortam sağlayan cihaz"]
];
